---

- name: "Test replace Apache ServerAlias"
  ansible.builtin.replace:
    path: /home/joffroy/ansible/data/http4.conf
    regexp: 'ServerAlias.*$'
    after: '<VirtualHost .*:{{ item.port }}'
    before: '</VirtualHost>'
    replace: ''

- name: "Test replace Apache ServerAlias"
  ansible.builtin.replace:
    path: /home/joffroy/ansible/data/http4.conf
    after: '<VirtualHost .*:{{ item.port }}>'
    before: '</VirtualHost>'
    regexp: '(ServerName.*)'
    replace: '\g<1>ServerAlias "{{ item.alias }}"'
  when: item.enable
