---

- name: Network Getting Started First Playbook
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: localhost

  vars:
    alias_dns: "http://rec.fr.fr"
  tasks:

    - name: "Display the config"
      ansible.builtin.debug:
        msg: "The hostname is {{ inventory_hostname }}"


    - name: "Test blockinfile"
      ansible.builtin.blockinfile:
        path: /home/joffroy/ansible/data/test1.conf
        block: |
          Mon bloc

    - name: "Test blockinfile Apache ServerAlias"
      ansible.builtin.blockinfile:
        path: /home/joffroy/ansible/data/http.conf
        marker: "    # {mark} ANSIBLE MANAGED BLOCK (Apache)"
        insertafter: '(?m)443(.|\n)*ServerName.*'
        block: '    Mon bloc 343'
        backup: true

    # - name: "Test replace Apache ServerAlias"
    #   ansible.builtin.replace:
    #     path: /home/joffroy/ansible/data/http2.conf
    #     regexp: '(.*ServerName.*)'
    #     after: '<VirtualHost .*:443>'
    #     before: '</VirtualHost>'
    #     replace: '\g<1>\n    ServerAlias "{{ alias_dns }}"'

    - name: "Update ServerAlias"
      when: true
      block:
        - name: "Test replace Apache ServerAlias"
          ansible.builtin.replace:
            path: /home/joffroy/ansible/data/http3.conf
            regexp: 'ServerAlias.*$'
            after: '<VirtualHost .*:443>'
            before: '</VirtualHost>'
            replace: ''

        - name: "Test replace Apache ServerAlias"
          ansible.builtin.replace:
            path: /home/joffroy/ansible/data/http3.conf
            after: '<VirtualHost .*:443>'
            before: '</VirtualHost>'
            regexp: '(ServerName.*$)'
            replace: '\g<1>ServerAlias "{{ alias_dns }}"'

    - name: "Update ServerAlias"
      when: true
      ansible.builtin.include_tasks: c.yml
      loop:
        - { port: 443, alias: "http://rec.fr.fr", enable: true}
        - { port: 8080, alias: "http://rec8.fr.fr", enable: true}
