---

- name: Network Getting Started First Playbook
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: localhost
  tasks:

    - name: Display the config
      debug:
        msg: "The hostname is {{ inventory_hostname }}"


    - name: "Test blockinfile"
      ansible.builtin.blockinfile:
        path: /home/joffroy/ansible/data/test1.conf
        block: |
          Mon bloc

    - name: "Test blockinfile Apache ServerAlias"
      ansible.builtin.blockinfile:
        path: /home/joffroy/ansible/data/http.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK (Apache)"
        insertafter: 'ServerName'
        block: |
          
